name: Deploy 3 Apps to EKS

on:
  push:
    branches:
      - main

# üîê Required for OIDC
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  ACCOUNT_ID: 131127508996

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # üîê Assume IAM Role using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::131127508996:role/GitHubActionsEKSRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # -------- APP 1 --------
      - name: Build & Push app1
        run: |
          docker build -t app1 ./app1
          docker tag app1:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/app1:latest
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/app1:latest

      # -------- APP 2 --------
      - name: Build & Push app2
        run: |
          docker build -t app2 ./app2
          docker tag app2:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/app2:latest
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/app2:latest

      # -------- APP 3 --------
      - name: Build & Push app3
        run: |
          docker build -t app3 ./app3
          docker tag app3:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/app3:latest
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/app3:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/app1-deployment.yaml
          kubectl apply -f k8s/app2-deployment.yaml
          kubectl apply -f k8s/app3-deployment.yaml
